[package]
name = "aoc_2022_7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs = "1.2.0"
lazy-regex = "2.3.2"
regex = "1.7.0"
